# Generated by Django 3.2.18 on 2023-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('titre', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('quentite', models.IntegerField()),
            ],
        ),
    ]
