# Generated by Django 3.2.18 on 2023-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_revenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.IntegerField(default=0),
        ),
    ]
