# Generated by Django 3.2.18 on 2023-03-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_prix_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Revenu',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_Image',
        ),
    ]
