# Generated by Django 3.2.18 on 2023-03-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_auto_20230303_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField()),
                ('temperateur', models.FloatField()),
                ('flow', models.FloatField()),
                ('level', models.FloatField()),
                ('gas', models.FloatField()),
                ('vibration', models.FloatField()),
            ],
        ),
    ]
