# Generated by Django 3.2.18 on 2023-03-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_etat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='etat',
        ),
    ]
