# Generated by Django 3.2.18 on 2023-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='percontage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField()),
                ('temperateur', models.FloatField()),
                ('flow', models.FloatField()),
                ('level', models.FloatField()),
                ('gas', models.FloatField()),
                ('vibration', models.FloatField()),
            ],
        ),
    ]
