# Generated by Django 3.2.18 on 2023-03-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='prblm',
            field=models.CharField(max_length=150),
        ),
    ]
