# Generated by Django 3.2.18 on 2023-03-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_solution_prblm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='prblm',
            field=models.IntegerField(),
        ),
    ]
